export const ActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  REMOVE_SELECTED_PRODUCTS: "REMOVE_SELECTED_PRODUCTS",
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  SEARCH_TERM: "SEARCH_TERM",
  SET_PREFERENCES: "SET_PREFERENCES",
};
